[book]
title = "Heatblur F-4E Phantom II"
description = "Manual of the F-4E Phantom by Heatblur Simulations."
authors = ["Heatblur Simulations", "Contributions from the Community"]
language = "en"
multilingual = false

[output.html]
git-repository-url = "https://github.com/Heatblur-Simulations/f-4e-manual"
edit-url-template = "https://github.com/Heatblur-Simulations/f-4e-manual/edit/master/{path}"
default-theme = "Navy"
additional-css = ['theme/catppuccin.css', 'theme/catppuccin-admonish.css']
mathjax-support = true
